name       : haste-client
version    : 1.0.2
release    : 1
source     :
    - https://pypi.python.org/packages/source/h/haste-client/haste-client-1.0.2.tar.gz : f54e6980fb88cef8ee19f668affc30a330efaff6f1d431134271a21b4f0a2e11
license    : MIT
summary    : haste-client
description: |
    haste client that sends text to http://www.hastebin.com
rundeps    :
    - python-requests
    - python-docopt
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
