name       : haste-client
version    : 1.0.3
release    : 2
source     :
    - https://github.com/jirutka/haste-client/archive/v1.0.3.tar.gz : c2fc02696b88672084e49dfade657eb563686ba194d72ecb419f692904012a81
license    : MIT
component  : system.utils
summary    : haste-client
description: |
    haste client that sends text to http://www.hastebin.com
rundeps    :
    - python-requests
    - python-docopt
build      : |
    %python_setup
install    : |
    %python_install --no-compile -O0
